name: decide_for_us
description: A decision-making app

publish_to: 'none'

version: 1.0.26+41

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CORE
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  shared_preferences: ^2.2.2

  # FIREBASE
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.2.0

  # PURCHASES
  purchases_flutter: ^9.16.0

  # LOCATION
  geolocator: ^11.0.0
  geocoding: ^2.1.1

  # UI / EFFECTS
  confetti: ^0.8.0
  share_plus: ^7.2.2
  audioplayers: ^5.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/spin.mp3
    - assets/sounds/win.mp3

