// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJG4ORHpnn9CGqXII2yN4IVsGXWnZHtE',
    appId: '1:573639270934:web:668cd0651d635d8d08cb37',
    messagingSenderId: '573639270934',
    projectId: 'decide-for-us-792bc',
    authDomain: 'decide-for-us-792bc.firebaseapp.com',
    storageBucket: 'decide-for-us-792bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sxH45pwh6WyL_Jy-YdiZmRzqhBYdR94',
    appId: '1:573639270934:android:5c8ab5014410949708cb37',
    messagingSenderId: '573639270934',
    projectId: 'decide-for-us-792bc',
    storageBucket: 'decide-for-us-792bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfp2yaEKkgNF0iKlVg8L5aJNyrR0A9iWk',
    appId: '1:573639270934:ios:98bbd1aeffa6db6f08cb37',
    messagingSenderId: '573639270934',
    projectId: 'decide-for-us-792bc',
    storageBucket: 'decide-for-us-792bc.firebasestorage.app',
    iosBundleId: 'com.example.decideClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfp2yaEKkgNF0iKlVg8L5aJNyrR0A9iWk',
    appId: '1:573639270934:ios:98bbd1aeffa6db6f08cb37',
    messagingSenderId: '573639270934',
    projectId: 'decide-for-us-792bc',
    storageBucket: 'decide-for-us-792bc.firebasestorage.app',
    iosBundleId: 'com.example.decideClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDJG4ORHpnn9CGqXII2yN4IVsGXWnZHtE',
    appId: '1:573639270934:web:29507c3ea036ff7f08cb37',
    messagingSenderId: '573639270934',
    projectId: 'decide-for-us-792bc',
    authDomain: 'decide-for-us-792bc.firebaseapp.com',
    storageBucket: 'decide-for-us-792bc.firebasestorage.app',
  );
}
